### ISSUE TITLE
If I only use one GPU, do I need to make any modifications to the original code?

### ISSUE THREAD

**Issue by tiesanguaixia** [yuqi657/video_language_model#1]
Hi! Thank you for your great work! I see that the running command you provided is for multi-GPU environments, so I ask this question. Thank you in advance!

**Comment by yuqi657** [comment]
I think you do not need to change code. Because I do some evaluation on 1 gpu and no error occurs. But if there is some error occur, you can modify some code according to the error information.

**Comment by LiuRicky** [comment]
> Hi! Thank you for your great work! I see that the running command you provided is for multi-GPU environments, so I ask this question. Thank you in advance!

I think you do not need to change code. Because I do some evaluation on 1 gpu and no error occurs. But if there is some error occur, you can modify some code according to the error information.
