### ISSUE TITLE
Token Mixing 的层数

### ISSUE THREAD

**Issue by Arsiuuu** [yuqi657/video_language_model#2]
您好，很荣幸拜读您的文章。文中提到因为尽可能少的计算所以只在vit的最后一层用了token mixing，请问您做过延伸到更多层数的实验吗？谢谢！

**Comment by yuqi657** [comment]
感谢提问，因为我们强调的重心是资源消耗，所以没有修改更多的层。但是感觉上来说修改过多层会影响性能，因为浅层需要建模空间信息，因此最好降低浅层的改动。

**Comment by yuqi657** [comment]
> 您好，很荣幸拜读您的文章。文中提到因为尽可能少的计算所以只在vit的最后一层用了token mixing，请问您做过延伸到更多层数的实验吗？谢谢！
感谢提问，因为我们强调的重心是资源消耗，所以没有修改更多的层。但是感觉上来说修改过多层会影响性能，因为浅层需要建模空间信息，因此最好降低浅层的改动。

**Comment by yuqi657** [comment]
> 您好，很荣幸拜读您的文章。文中提到因为尽可能少的计算所以只在vit的最后一层用了token mixing，请问您做过延伸到更多层数的实验吗？谢谢！

感谢提问，因为我们强调的重心是资源消耗，所以没有修改更多的层。但是感觉上来说修改过多层会影响性能，因为浅层需要建模空间信息，因此最好降低浅层的改动。

**Comment by LiuRicky** [comment]
> 您好，很荣幸拜读您的文章。文中提到因为尽可能少的计算所以只在vit的最后一层用了token mixing，请问您做过延伸到更多层数的实验吗？谢谢！

感谢关注，因为我们强调的重心是资源消耗，所以没有修改更多的层。但是感觉上来说修改过多层会影响性能，因为浅层需要建模空间信息，因此最好降低浅层的改动。

**Comment by Arsiuuu** [comment]
谢谢您的启发~

**Comment by Arsiuuu** [comment]
您能告诉我视频任务的 config 是在几个GPU下运行的吗

**Comment by LiuRicky** [comment]
> 您能告诉我视频任务的 config 是在几个GPU下运行的吗

记不太清了,好像是8卡V100,因为BLIP有个ITM模块太占显存了,训练过程不加ITM的话应该会节省很多.
